# Generated by Django 2.0.7 on 2018-08-13 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='when',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
